/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import UTIL.AtbValue;
import UTIL.Atributo;
import UTIL.Base;
import UTIL.Checker;
import UTIL.DataAccess;
import UTIL.ManageData;

/**
 *
 * @author a120106
 */
public class Principal extends javax.swing.JFrame {

    DataAccess access;
    ManageData data;
    Base caso;

    public Principal() {
        initComponents();
        caso = new Base();
        access = new DataAccess();
        access.setAtributos("data/atributos.csv");
        access.setPesos("data/pesos.csv");
        access.setBase("data/base.csv");
        data = access.getBaseCompleta();
        int n = access.getBaseCompleta().getAtributos().size();
        Atributo at = access.getBaseCompleta().getAtributos().get(0);
        for (int i = 0; i < at.getValor().size(); i++) {
            jLabel2.setText(at.getAtributo());
            caixa1.addItem(at.getValor().get(access.getAtrbName().get(i)));

        }
        
        porc.setText(barra.getValue()+"%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        caixa1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        percentual = new javax.swing.JLabel();
        barra = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        porc = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Problemas da Soja");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Proximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        caixa1.setName("ComboBox"); // NOI18N
        caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 44)); // NOI18N
        jLabel1.setText("Insira os dados:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("###");

        percentual.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        percentual.setForeground(new java.awt.Color(0, 0, 255));
        percentual.setText("0");

        barra.setMinimum(30);
        barra.setValue(80);
        barra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraStateChanged(evt);
            }
        });

        jLabel3.setText("Percentual mínimo:");

        porc.setText("%%%");

        jButton2.setText("Ver base");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(porc)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(percentual)
                                    .addGap(17, 17, 17))
                                .addComponent(caixa1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addComponent(barra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(percentual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(porc))
                .addGap(1, 1, 1)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void caixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa1ActionPerformed


    }//GEN-LAST:event_caixa1ActionPerformed

    private void barraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraStateChanged
        porc.setText(barra.getValue()+"%");
    }//GEN-LAST:event_barraStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Final f = new Final();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    int x = 0;

    private void generate() {
        AtbValue atb = null;
        Atributo at = null;
        try {
            int n = access.getBaseCompleta().getAtributos().size();

            if (x == 0) {
                at = access.getBaseCompleta().getAtributos().get(0);
            } else {
                at = access.getBaseCompleta().getAtributos().get(n - x);
            }

            atb = new AtbValue(at.getAtributo(), caixa1.getSelectedItem().toString());
            System.out.println(atb.toString());
            caso.getAtbValues().add(atb);
            System.out.println("Added!");
        } catch (Exception e) {
            System.out.println("Sem itens!\n" + e);
        }
        try {
            int p = -1, b = -1;
            int t = at.getValor().size();
//            for (int i = 0; i < data.getBase().get(i).getAtbValues().size(); i++) {
//
//                if (data.getBase().get(0).getAtbValues().get(i).getAtributo().equals(atb.getAtributo())) {
//                    System.out.println(data.getBase().get(0).getAtbValues().get(i).toString());
//
//                }
//            }
            for (int i = 0; i < at.getValor().size() - 1; i++) {
                if (atb.getValor().equals("Desconhecido")) {
                    p = -1;
                }
                if (atb.getValor().equals(at.getValor().get(i + ""))) {
                    p = i;
                }
            }
            //for (int i = 0; i < 2; i++) {
            for (int i = 0; i < data.getBase().size(); i++) {
                for (int j = 0; j < at.getValor().size() - 1; j++) {
                    for (int k = 0; k < data.getBase().get(i).getAtbValues().size(); k++) {
                        AtbValue atbb = data.getBase().get(i).getAtbValues().get(k);
                        if (atbb.getValor().equals("Desconhecido")) {
                            b = -1;
                        }
                        if ((atbb.getValor().equals(at.getValor().get(j + "")))&&atbb.getAtributo().equals(at.getAtributo())) {
                            b = j;
                            //System.out.println("P: "+p+" |B: "+b+" |T: "+(t-1));
                            atbb.setSl(Checker.similaridadeLocal(p, b, (t - 2)));
                            //System.out.println("Similaridade Local do Caso '" + data.getBase().get(i).getAtbValues().get(0).getValor() + "':" + atbb.getSl());
                            k = data.getBase().get(i).getAtbValues().size() + 1;
                            j = at.getValor().size();
                        }

                    }

                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        caixa1.removeAllItems();
        int n = access.getBaseCompleta().getAtributos().size();
        percentual.setText((x+1)+"");
        if (x == n - 1) {
            System.out.println("Tudo calculado! Só fazer a global aqui dentro!");
            Checker.similaridadeGlobal(data);
            data.sort();
            for(int i=0; i<data.getBase().size(); i++){
                System.out.println(data.getBase().get(i));
            }
            this.dispose();
            Respostas r = new Respostas(data, barra.getValue(), caso);
            r.setVisible(true);
            
        } else {
            x++;
            at = access.getBaseCompleta().getAtributos().get(n - x);
            for (int i = 0; i < at.getValor().size(); i++) {
                jLabel2.setText(at.getAtributo());
                caixa1.addItem(at.getValor().get(access.getAtrbName().get(i)));

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barra;
    private javax.swing.JComboBox<String> caixa1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel percentual;
    private javax.swing.JLabel porc;
    // End of variables declaration//GEN-END:variables
}
